### ISSUE TITLE
Bug: survival items is being marked as creative

### ISSUE THREAD

**Issue by viet** [lectron/creative-survival#8]
When I hold survival item, and change my game mode to creative, the survival item is marked as creative and has lore, and disappear when I drop them.

I need a fix on this one. Thanks.

**Comment by Skyvko6607** [comment]
I have checked and I couldn't reproduce the error. It worked fine for me.
Can you tell me how to reproduce the error so I could fix it?

**Comment by viet** [comment]
what is your minecraft IGN? I can add you as a rank with creative on my server mc.lectron.com to test out for yourself.

**Comment by Skyvko6607** [comment]
Skyvko6607
